### ISSUE TITLE
my menu is broken

### ISSUE THREAD

**Issue by JinxAgain** [Dhyfer1/Dracula-for-EverythingToolbar#1]
it happens every time when i reboot my computer.
![image](https://user-images.githubusercontent.com/64463709/172305874-e1e2ad14-3484-43d2-b249-6a812ed9d88b.png)
change to the original theme, it be all right again.
BTW, i am using start11, don't know if has something to do with it.

**Comment by Dhyfer1** [comment]
Hi @JinxAgain, thanks for using my EverythingToolbar theme.

Well, I'm not using Windows 10 anymore. I'm using Windows 11 and EverythingToolbar doesn't work in Windows 11 because it can't be integrated to the taskbar like it did in Windows 10, so EverythingToolbar only works in Windows 10 for the moment.

On my PC I have space to create a partition to install Windows 10, install EverythingToolbar and check your problem, just give me some time to check it (in the course of this week or next). And in the meantime, the problem with the context menu you are showing in the image may be because you are using Start11. Have you tried EverythingToolbar with my theme and without Start11?

**Comment by JinxAgain** [comment]
yeah, i will try that. thanks anyway.

**Comment by Dhyfer1** [comment]
Hello again @JinxAgain

I have updated my theme, so download it again. When I first created my theme there was no option to edit the context menu colors, but now that EverythingToolbar author added those options then I have edited some values in the theme file. So my theme is already updated. 

By the way, I found out why the context menu becomes transparent as you showed in your image, and it happens because you press the space bar while the context menu is open, that's the cause and I was able to check it out for myself.

That's all. Do you like how the context menu looks with my updated theme now?

**Comment by JinxAgain** [comment]
It works like a charm, I love this new menu. 

And I'm quit sure that I didn't press the space bar at least for my case.

Very appreciate your hard work.
